import type { Metadata } from "next";
import { Work_Sans as Work } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

const work = Work({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn("min-h-screen bg-background antialiased", work.className)}>
                <Navbar />
                {children}
            </body>
        </html >
    );
}
